# Week 03: Python libraries

## Importing a module

In [ ]:
# import the modules

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

## Getting started with Numpy

The Numpy documentation can be found [here](https://numpy.org/)

In [ ]:
# Create a simple array

a = np.array([1, 2, 3])
print('a: ', type(a))

b = np.array((1, 2, 3))
print('b: ', type(b))

a:  <class 'numpy.ndarray'>
b:  <class 'numpy.ndarray'>


In [ ]:
# Creating an array of ones

a = np.ones((3,4), dtype=np.int8)
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [ ]:
# What if we want a matrix with the same values?

a = np.full((3,4),0.111)
print(a)

[[0.111 0.111 0.111 0.111]
 [0.111 0.111 0.111 0.111]
 [0.111 0.111 0.111 0.111]]


In [ ]:
# Getting evenly spaced values within the range

a = np.arange(0, 5/3, 0.667)
print(a)

b = np.arange(0, 2, 0.3)
print(b)

[0.    0.667 1.334]
[0.  0.3 0.6 0.9 1.2 1.5 1.8]


In [ ]:
# Creating an evenly spaced array(?)

a = np.linspace(0, 5/3, 6)
print(a)

# Question: How is it any different from arange?

[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667]


In [ ]:
# Generating random numbers

a = np.random.rand(2,3)
print(a)

[[0.73510097 0.70731485 0.83903674]
 [0.28526857 0.9356788  0.62867119]]


In [ ]:
# Empty?

b = np.empty((2,3),dtype=None)
print(b)

print('b: ', type(b))

[[0.73510097 0.70731485 0.83903674]
 [0.28526857 0.9356788  0.62867119]]
b:  <class 'numpy.ndarray'>


## Why Numpy and Pandas over regular Python arrays?

### Easier to assign values over a slice of an array



In [ ]:
# Numpy array

a = np.array([1,2,5,7,8])

In [ ]:
a[1:3] = -1

In [ ]:
a

array([ 1, -1, -1,  7,  8])

In [ ]:
# Regular Python array

b = [1,2,5,7,8]
print(b)

[1, 2, 5, 7, 8]


In [ ]:
b[1:3] = -1

TypeError: ignored

### ndarray slices, if modified will modify the original array as well

In [ ]:
# Numpy array slice

a = np.array([1,2,5,7,8])

In [ ]:
a_slice = a[1:5]

print(a_slice)

[2 5 7 8]


In [ ]:
a_slice[1] = 1000

In [ ]:
a

# Question: Why is it not 1,2,1000,5,7,8?

array([   1,    2, 1000,    7,    8])

In [ ]:
# Regular python array slice

a = [1,2,5,7,8]
b = a[1:5]

In [ ]:
b[1] = 1000

In [ ]:
print(a)

print('b: ', b)

[1, 2, 5, 7, 8]
b:  [2, 1000, 7, 8]


## Understanding Pandas with an Example

The Pandas documentation can be found [here](https://pandas.pydata.org/)

We will be understanding Pandas with the help of an example

In [ ]:
from google.colab import files
files.upload()

Saving pokemon_data.csv to pokemon_data.csv


{'pokemon_data.csv': b"#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary\n1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,FALSE\n2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,FALSE\n3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,FALSE\n3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,FALSE\n4,Charmander,Fire,,39,52,43,60,50,65,1,FALSE\n5,Charmeleon,Fire,,58,64,58,80,65,80,1,FALSE\n6,Charizard,Fire,Flying,78,84,78,109,85,100,1,FALSE\n6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,1,FALSE\n6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,1,FALSE\n7,Squirtle,Water,,44,48,65,50,64,43,1,FALSE\n8,Wartortle,Water,,59,63,80,65,80,58,1,FALSE\n9,Blastoise,Water,,79,83,100,85,105,78,1,FALSE\n9,BlastoiseMega Blastoise,Water,,79,103,120,135,115,78,1,FALSE\n10,Caterpie,Bug,,45,30,35,20,20,45,1,FALSE\n11,Metapod,Bug,,50,20,55,25,25,30,1,FALSE\n12,Butterfree,Bug,Flying,60,45,50,90,80,70,1,FALSE\n13,Weedle,Bug,Poison,40,35,30,20,20,50,1,F

### Initialization

In [ ]:
# Use pd.Series()

a = pd.Series([1,2,5,7,8])
a

0    1
1    2
2    5
3    7
4    8
dtype: int64

In [ ]:
print('Data passed as a list')
df_list = pd.DataFrame([['May1', 32], ['May2', 35], ['May3', 40], ['May4', 50]])
print(df_list)

Data passed as a list
      0   1
0  May1  32
1  May2  35
2  May3  40
3  May4  50


In [ ]:
print('Data passed as dictionary')
df_dict = pd.DataFrame({"A": [1, 2, 3], "B": [4, 5, 6]},dtype = float)
print(df_dict)

Data passed as dictionary
     A    B
0  1.0  4.0
1  2.0  5.0
2  3.0  6.0


### Column and Indexes

In case of dictionary the keys would act as columns but in lists, the column names if not specified will start as '0' as the 1st column, '1' as the 2nd Column and so on.</br>
The left most part of the dataframe is called as index, it's starts default with index 0.

In [ ]:
# Listing the columns

print(df_dict.columns)

Index(['A', 'B'], dtype='object')


In [ ]:
# Rename columns
df_dict.rename(columns={'A':'apple'},inplace=True)
df_dict


# inplace by default is false
# if inplace = True is not set then the changes are not made on the original df but only a temp df is made with changes


apple    B
0    1.0  4.0
1    2.0  5.0
2    3.0  6.0

In [ ]:
# changes made for original df

df_dict.rename(columns={'A':'c'},inplace=False)
df_dict

apple    B
0    1.0  4.0
1    2.0  5.0
2    3.0  6.0

In [ ]:
# Reset column names
# Tip: remember to pass the entire list in this case

df_dict.columns = ['a', 'b']
df_dict.head()

a    b
0  1.0  4.0
1  2.0  5.0
2  3.0  6.0

In [ ]:
# Defining columns, index during dataframe creation

df_temp = pd.DataFrame([['Oct6', 60], ['Oct7', 83], ['Oct8', 74], ['Oct9', 80]], index=['Day 1', 'Day 2', 'Day 3', 'Day 4'], columns = ['October', 'Temperature'])
df_temp

October  Temperature
Day 1    Oct6           60
Day 2    Oct7           83
Day 3    Oct8           74
Day 4    Oct9           80

`reset_index`: To drop index and bring pandas default sequential form of 0, 1, ...

In [ ]:
# Here drop=True means we want to drop the original index we have and reset to default value

df_temp.reset_index(drop=True, inplace=False)

October  Temperature
0    Oct6           60
1    Oct7           83
2    Oct8           74
3    Oct9           80

In [ ]:
# We can also make a column as index

df_temp = pd.DataFrame([['Oct6', 60], ['Oct7', 83], ['Oct8', 74], ['Oct9', 80]], columns = ['October', 'Temperature'])
df_temp.set_index('October')

Temperature
October             
Oct6              60
Oct7              83
Oct8              74
Oct9              80

In [ ]:
# Reading data from a csv file
# index_col describes which column we want to set as the index
# head function is used to print first n rows of the dataframe, here n=10 in our case

pokemon_data = pd.read_csv('pokemon_data.csv', index_col=0)
pokemon_data.head()

Name Type 1  Type 2  ...  Speed  Generation  Legendary
#                                        ...                              
1              Bulbasaur  Grass  Poison  ...     45           1      False
2                Ivysaur  Grass  Poison  ...     60           1      False
3               Venusaur  Grass  Poison  ...     80           1      False
3  VenusaurMega Venusaur  Grass  Poison  ...     80           1      False
4             Charmander   Fire     NaN  ...     65           1      False

[5 rows x 11 columns]

### Basic Data Statistics

In [ ]:
#describe function will compute basic statistics as shown below as for each column

pokemon_data.describe()

#Note: Stats are not calculated for object or string dtype

HP      Attack     Defense  ...     Sp. Def       Speed  Generation
count  800.000000  800.000000  800.000000  ...  800.000000  800.000000   800.00000
mean    69.258750   79.001250   73.842500  ...   71.902500   68.277500     3.32375
std     25.534669   32.457366   31.183501  ...   27.828916   29.060474     1.66129
min      1.000000    5.000000    5.000000  ...   20.000000    5.000000     1.00000
25%     50.000000   55.000000   50.000000  ...   50.000000   45.000000     2.00000
50%     65.000000   75.000000   70.000000  ...   70.000000   65.000000     3.00000
75%     80.000000  100.000000   90.000000  ...   90.000000   90.000000     5.00000
max    255.000000  190.000000  230.000000  ...  230.000000  180.000000     6.00000

[8 rows x 7 columns]

In [ ]:
#Check the type of each column it will be Series datatype

print(pokemon_data.dtypes)

Name          object
Type 1        object
Type 2        object
HP             int64
Attack         int64
Defense        int64
Sp. Atk        int64
Sp. Def        int64
Speed          int64
Generation     int64
Legendary       bool
dtype: object


In [ ]:
# Value counts for type 2

pokemon_data['Type 2'].value_counts()

Flying      97
Ground      35
Poison      34
Psychic     33
Fighting    26
Grass       25
Fairy       23
Steel       22
Dark        20
Dragon      18
Ghost       14
Water       14
Ice         14
Rock        14
Fire        12
Electric     6
Normal       4
Bug          3
Name: Type 2, dtype: int64

In [ ]:
# Calculate mean, max, min, std, sum

print(pokemon_data['HP'].describe())

count    800.000000
mean      69.258750
std       25.534669
min        1.000000
25%       50.000000
50%       65.000000
75%       80.000000
max      255.000000
Name: HP, dtype: float64


### Axis management

axis denotes the dimension of dataframe. </br>
axis = 0, also the axis of index/rows. Thus calculations are done at column level. </br>
axis = 1, also axis of columns. Calculations are done for each row </br>
For added clarity, you can specify axis='index' (instead of axis=0) or axis='columns' (instead of axis=1).

In [ ]:
df_dummy = pd.DataFrame([[2,-2],[1,-1]])
df_dummy

0  1
0  2 -2
1  1 -1

In [ ]:
# summation on axis 0 or for each row

df_dummy.sum(axis=0)

0    3
1   -3
dtype: int64

In [ ]:
# summation on axis 1 or for each column

df_dummy.sum(axis=1)

0    0
1    0
dtype: int64

### NaN

NaN (Not a Number) is a special floating point number (like infinity) and is an indication of no data.

In [ ]:
df_nan = pd.DataFrame([{'a': 1, 'b': 2}, {'a': 5, 'b': 10, 'c': 20}])
print(df_nan)

# Notice that column c is of type float due to NaN

   a   b     c
0  1   2   NaN
1  5  10  20.0


In [ ]:
# isnull working - assigns each data point in the dataframe with True or False
# return dataframe filled with True or False

print(df_nan.isnull())

       a      b      c
0  False  False   True
1  False  False  False


In [ ]:
# To count how many NaN, use sum function on the result of isnull

print(df_nan.isnull().sum())

a    0
b    0
c    1
dtype: int64


In [ ]:
# Question: Which columns in the Pokemon data set have null values?



### Data Manipulation

In [ ]:
df = pd.DataFrame([['May1',32],['May2',35],['May3',40],['May4',50]],index = ['Day1','Day2','Day3','Day4'],columns = ['Month','Temperature'])

df

Month  Temperature
Day1  May1           32
Day2  May2           35
Day3  May3           40
Day4  May4           50

In [ ]:
# Access column by name

print(df['Temperature'])

Day1    32
Day2    35
Day3    40
Day4    50
Name: Temperature, dtype: int64


In [ ]:
# Multiple column access

df[['Temperature', 'Month']]

Temperature Month
Day1           32  May1
Day2           35  May2
Day3           40  May3
Day4           50  May4

In [ ]:
print(type(df.iloc[1]))
print(df.iloc[1])

<class 'pandas.core.series.Series'>
Month          May2
Temperature      35
Name: Day2, dtype: object


In [ ]:
print('range of index wise selection in discrete manner')
print(df.iloc[[1,2,3]])

range of index wise selection in discrete manner
     Month  Temperature
Day2  May2           35
Day3  May3           40
Day4  May4           50


In [ ]:
print('Get single value')
print()
print(df.iloc[0])
print()

print(df.iloc[0,0])

Get single value

Month          May1
Temperature      32
Name: Day1, dtype: object

May1


In [ ]:
# Question: Select the first five columns of the Pokemon dataset



In [ ]:
# Adding columns
# Notice the difference

add_column = pd.Series(['St. Marks Ave', 'Carlton', 'Jay Street', '88th Street'], index = ['Day 1', 'Day 2', 'Day 3', 'Day 4'])
df['Stations'] = add_column
df['Stations 2'] = pd.Series(['St. Marks Ave', 'Carlton', 'Jay Street', '88th Street'])
print(df)
print()

# either specify index or add as python list instead of series
df['Stations 2'] = ['St. Marks Ave', 'Carlton', 'Jay Street', '88th Street']
print(df)

     Month  Temperature Stations Stations 2
Day1  May1           32      NaN        NaN
Day2  May2           35      NaN        NaN
Day3  May3           40      NaN        NaN
Day4  May4           50      NaN        NaN

     Month  Temperature Stations     Stations 2
Day1  May1           32      NaN  St. Marks Ave
Day2  May2           35      NaN        Carlton
Day3  May3           40      NaN     Jay Street
Day4  May4           50      NaN    88th Street


In [ ]:
# New column using existing column

df['Wind Speed'] = df['Temperature']*0.414
print(df)

     Month  Temperature Stations     Stations 2  Wind Speed
Day1  May1           32      NaN  St. Marks Ave      13.248
Day2  May2           35      NaN        Carlton      14.490
Day3  May3           40      NaN     Jay Street      16.560
Day4  May4           50      NaN    88th Street      20.700


In [ ]:
# Column addition (with same data type)

df['Add_temp_wind'] = df['Wind Speed'] + df['Temperature']
print(df)

     Month  Temperature Stations     Stations 2  Wind Speed  Add_temp_wind
Day1  May1           32      NaN  St. Marks Ave      13.248         45.248
Day2  May2           35      NaN        Carlton      14.490         49.490
Day3  May3           40      NaN     Jay Street      16.560         56.560
Day4  May4           50      NaN    88th Street      20.700         70.700


In [ ]:
# Changing values using loc/iloc

df.iloc[0,0] = 'May11'
df

Month  Temperature Stations     Stations 2  Wind Speed  Add_temp_wind
Day1  May11           32      NaN  St. Marks Ave      13.248         45.248
Day2   May2           35      NaN        Carlton      14.490         49.490
Day3   May3           40      NaN     Jay Street      16.560         56.560
Day4   May4           50      NaN    88th Street      20.700         70.700

In [ ]:
# drop function can be used to drop based on column or index 



In [ ]:
# Drop row of a dataframe use drop function and pass the indexed index or name of that index



# inplace=False

In [ ]:
# By index name



In [ ]:
# Question: Select data for temperature and wind speed column by using the loc method
# Hint: data.loc['Condition(s)']



In [ ]:
# Condition based filtering

# Conditions generate a mask df of booleans which is used to select relevant rows from original dataframe



In [ ]:
# Selection part



In [ ]:
# Complex selection



In [ ]:
# Question: What is the count of pokemon that have 'null' in type 2?



In [ ]:
# Getting unique values for column 'Type 1' with help of unique function
# The return type is ndarray which consist of n rows and columns 
# (18,) - Represents 18 rows and 1 column 

print(pokemon_data['Type 1'].unique())

['Grass' 'Fire' 'Water' 'Bug' 'Normal' 'Poison' 'Electric' 'Ground'
 'Fairy' 'Fighting' 'Psychic' 'Rock' 'Ghost' 'Ice' 'Dragon' 'Dark' 'Steel'
 'Flying']


### Data cleanup

In [ ]:
# removing null containing rows

pokemon_data.dropna()

# since inplace is not set, values/rows will not be removed

Name   Type 1  Type 2  ...  Speed  Generation  Legendary
#                                            ...                              
1                Bulbasaur    Grass  Poison  ...     45           1      False
2                  Ivysaur    Grass  Poison  ...     60           1      False
3                 Venusaur    Grass  Poison  ...     80           1      False
3    VenusaurMega Venusaur    Grass  Poison  ...     80           1      False
6                Charizard     Fire  Flying  ...    100           1      False
..                     ...      ...     ...  ...    ...         ...        ...
719                Diancie     Rock   Fairy  ...     50           6       True
719    DiancieMega Diancie     Rock   Fairy  ...    110           6       True
720    HoopaHoopa Confined  Psychic   Ghost  ...     70           6       True
720     HoopaHoopa Unbound  Psychic    Dark  ...     80           6       True
721              Volcanion     Fire   Water  ...     70           6       True

[414 rows x 11 columns]

In [ ]:
# Masking and use of loc
# Converting to string datatype with astype

pokemon_data['Type 2'] = pokemon_data['Type 2'].astype(str)
mask = (pokemon_data['Type 2']!= 'nan')

pk_data = pokemon_data.loc[mask]
pk_data

Name   Type 1  Type 2  ...  Speed  Generation  Legendary
#                                            ...                              
1                Bulbasaur    Grass  Poison  ...     45           1      False
2                  Ivysaur    Grass  Poison  ...     60           1      False
3                 Venusaur    Grass  Poison  ...     80           1      False
3    VenusaurMega Venusaur    Grass  Poison  ...     80           1      False
6                Charizard     Fire  Flying  ...    100           1      False
..                     ...      ...     ...  ...    ...         ...        ...
719                Diancie     Rock   Fairy  ...     50           6       True
719    DiancieMega Diancie     Rock   Fairy  ...    110           6       True
720    HoopaHoopa Confined  Psychic   Ghost  ...     70           6       True
720     HoopaHoopa Unbound  Psychic    Dark  ...     80           6       True
721              Volcanion     Fire   Water  ...     70           6       True

[414 rows x 11 columns]

### Sort

In [ ]:
# Can assign one or more column for sorting
# Return type is dataframe object

pokemon_data.sort_values(by=['HP', 'Attack', 'Defense', 'Speed'], ascending = [False, True, False, True], inplace=True)
pokemon_data.head()

Name   Type 1 Type 2   HP  ...  Sp. Def  Speed  Generation  Legendary
#                                    ...                                       
242    Blissey   Normal    nan  255  ...      135     55           2      False
113    Chansey   Normal    nan  250  ...      105     50           1      False
202  Wobbuffet  Psychic    nan  190  ...       58     33           2      False
321    Wailord    Water    nan  170  ...       45     60           3      False
594  Alomomola    Water    nan  165  ...       45     65           5      False

[5 rows x 11 columns]

### Groupby

In [ ]:
# Normal Group by

pokemon_data.groupby('Type 1').head(1)

# The above code displays the top row within each group.

Name    Type 1   Type 2  ...  Speed  Generation  Legendary
#                                           ...                              
242             Blissey    Normal      nan  ...     55           2      False
202           Wobbuffet   Psychic      nan  ...     33           2      False
321             Wailord     Water      nan  ...     60           3      False
426            Drifblim     Ghost   Flying  ...     80           4      False
297            Hariyama  Fighting      nan  ...     50           3      False
716             Xerneas     Fairy      nan  ...     99           6       True
717             Yveltal      Dark   Flying  ...     99           6       True
646  KyuremWhite Kyurem    Dragon      Ice  ...     95           5       True
699             Aurorus      Rock      Ice  ...     58           6      False
673              Gogoat     Grass      nan  ...     68           6      False
244               Entei      Fire      nan  ...    100           2       True
464           Rhyperior    Ground     Rock  ...     40           4      False
365             Walrein       Ice    Water  ...     65           3      False
89                  Muk    Poison      nan  ...     50           1      False
385             Jirachi     Steel  Psychic  ...    100           3       True
181            Ampharos  Electric      nan  ...     55           2      False
469             Yanmega       Bug   Flying  ...     95           4      False
715             Noivern    Flying   Dragon  ...    123           6      False

[18 rows x 11 columns]

In [ ]:
# Aggregate Functions on groups

pokemon_data.groupby('Type 1').mean()

HP      Attack     Defense  ...       Speed  Generation  Legendary
Type 1                                       ...                                   
Bug       56.884058   70.971014   70.724638  ...   61.681159    3.217391   0.000000
Dark      66.806452   88.387097   70.225806  ...   76.161290    4.032258   0.064516
Dragon    83.312500  112.125000   86.375000  ...   83.031250    3.875000   0.375000
Electric  59.795455   69.090909   66.295455  ...   84.500000    3.272727   0.090909
Fairy     74.117647   61.529412   65.705882  ...   48.588235    4.117647   0.058824
Fighting  69.851852   96.777778   65.925926  ...   66.074074    3.370370   0.000000
Fire      69.903846   84.769231   67.769231  ...   74.442308    3.211538   0.096154
Flying    70.750000   78.750000   66.250000  ...  102.500000    5.500000   0.500000
Ghost     64.437500   73.781250   81.187500  ...   64.343750    4.187500   0.062500
Grass     67.271429   73.214286   70.800000  ...   61.928571    3.357143   0.042857
Ground    73.781250   95.750000   84.843750  ...   63.906250    3.156250   0.125000
Ice       72.000000   72.750000   71.416667  ...   63.458333    3.541667   0.083333
Normal    77.275510   73.469388   59.846939  ...   71.551020    3.051020   0.020408
Poison    67.250000   74.678571   68.821429  ...   63.571429    2.535714   0.000000
Psychic   70.631579   71.456140   67.684211  ...   81.491228    3.385965   0.245614
Rock      65.363636   92.863636  100.795455  ...   55.909091    3.454545   0.090909
Steel     65.222222   92.703704  126.370370  ...   55.259259    3.851852   0.148148
Water     72.062500   74.151786   72.946429  ...   65.964286    2.857143   0.035714

[18 rows x 8 columns]

In [ ]:
# groupby with more than 1 column order in which columns are specified is important



## Data Visualization

Access the Matplotlib documentation from [here](https://matplotlib.org/) and Seaborn documentation from [here](https://seaborn.pydata.org/)

In [ ]:
from google.colab import files
files.upload()

In [ ]:
# Read and display the file

pokemon_data = pd.read_csv('pokemon_data.csv', index_col = 0)
pokemon_data.head()

### Seaborn's plotting functions

In [ ]:
# Recommended way



In [ ]:
# Scatterplot arguments



### Customizing with Matplotlib

Matplotlib comes in handy when it comes to setting your axes limits. In order to do that -

1. Invoke your seaborn plotting function as normal
2. Invoke Matplotlib's customization functions. In this case, we will use its `ylim()` and `xlim()` functions

In [ ]:
# Plot using Seaborn



### Role of Pandas

In [ ]:
# boxplot



In [ ]:
# We can remove generation and Legendary as they are not combat stats

# Pre-format dataframe


# New boxplot


### Histogram